"""create initial schema

Revision ID: 73864e11322c
Revises: 
Create Date: 2026-07-12 11:51:29.678225
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73864e11322c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── PostgreSQL extensions (must be first) ─────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_useful_life_months', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['asset_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_asset_categories_parent', 'asset_categories', ['parent_category_id'], unique=False)
    op.create_index('UK_asset_categories_name_lower', 'asset_categories', [sa.text('lower(name)')], unique=True)
    op.create_table('asset_locations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('parent_location_id', sa.UUID(), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("location_type IN ('Site','Building','Floor','Room','Desk','Warehouse')", name='CK_asset_locations_type'),
    sa.ForeignKeyConstraint(['parent_location_id'], ['asset_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_asset_locations_parent', 'asset_locations', ['parent_location_id'], unique=False)
    op.create_index('IDX_asset_locations_type', 'asset_locations', ['location_type'], unique=False)
    op.create_table('authentication_providers',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('UK_auth_providers_name', 'authentication_providers', ['name'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('head_employee_id', sa.UUID(), nullable=True),
    sa.Column('parent_department_id', sa.UUID(), nullable=True),
    sa.Column('primary_location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Active','Inactive')", name='CK_departments_status'),
    # NOTE: FKs to users/employees added after those tables exist (see op.create_foreign_key below)
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_location_id'], ['asset_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('IDX_departments_head', 'departments', ['head_employee_id'], unique=False)
    op.create_index('IDX_departments_parent', 'departments', ['parent_department_id'], unique=False)
    op.create_index('IDX_departments_status', 'departments', ['status'], unique=False)
    op.create_index('UK_departments_code', 'departments', ['code'], unique=True, postgresql_where=sa.text('code IS NOT NULL'))
    op.create_table('dim_asset',
    sa.Column('asset_sk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('asset_sk')
    )
    op.create_index('IDX_dim_asset_current', 'dim_asset', ['asset_id'], unique=False, postgresql_where=sa.text('is_current = TRUE'))
    op.create_index('IDX_dim_asset_natural', 'dim_asset', ['asset_id', 'is_current'], unique=False)
    op.create_table('dim_category',
    sa.Column('category_sk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_sk')
    )
    op.create_index('IDX_dim_category_natural', 'dim_category', ['category_id', 'is_current'], unique=False)
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('date_key'),
    sa.UniqueConstraint('full_date')
    )
    op.create_index('IDX_dim_date_full_date', 'dim_date', ['full_date'], unique=False)
    op.create_table('dim_department',
    sa.Column('department_sk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_name', sa.String(length=150), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('department_sk')
    )
    op.create_index('IDX_dim_department_natural', 'dim_department', ['department_id', 'is_current'], unique=False)
    op.create_table('dim_employee',
    sa.Column('employee_sk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('employee_sk')
    )
    op.create_index('IDX_dim_employee_natural', 'dim_employee', ['employee_id', 'is_current'], unique=False)
    op.create_table('dim_time_of_day',
    sa.Column('time_key', sa.SmallInteger(), nullable=False),
    sa.Column('hour_label', sa.String(length=10), nullable=False),
    sa.Column('is_business_hour', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('time_key')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Active','Inactive')", name='CK_employees_status'),
    # department_id FK is DEFERRABLE — added via ALTER TABLE after both tables exist
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ondelete='SET NULL'),
    # user_id FK added after users table is created (see op.create_foreign_key below)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('IDX_employees_department', 'employees', ['department_id'], unique=False)
    op.create_index('IDX_employees_manager', 'employees', ['reporting_manager_id'], unique=False)
    op.create_index('IDX_employees_search', 'employees', ['department_id', 'status'], unique=False, postgresql_include=['id', 'employee_code'])
    op.create_index('IDX_employees_status', 'employees', ['status'], unique=False)
    op.create_index('UK_employees_code', 'employees', ['employee_code'], unique=True)
    op.create_index('UK_employees_user', 'employees', ['user_id'], unique=True)
    op.create_table('entity_code_sequences',
    sa.Column('entity_prefix', sa.String(length=10), nullable=False),
    sa.Column('current_value', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('padding_length', sa.SmallInteger(), server_default=sa.text('4'), nullable=False),
    sa.PrimaryKeyConstraint('entity_prefix')
    )
    op.create_table('maintenance_technicians',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('is_external_vendor', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('vendor_name', sa.String(length=150), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_maintenance_technicians_active', 'maintenance_technicians', ['is_active'], unique=False)
    op.create_index('IDX_maintenance_technicians_specialization', 'maintenance_technicians', ['specialization'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('IDX_permissions_module', 'permissions', ['module_name'], unique=False)
    op.create_index('PK_permissions', 'permissions', ['id'], unique=False)
    op.create_index('UK_permissions_name', 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('PK_roles', 'roles', ['id'], unique=False)
    op.create_index('UK_roles_name', 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Active','Inactive','Suspended','Deletion Pending','Deleted')", name='CK_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('IDX_users_locked', 'users', ['locked_until'], unique=False, postgresql_where=sa.text('locked_until IS NOT NULL'))
    op.create_index('IDX_users_status', 'users', ['status'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('Create','Update','Delete','Approve','Reject','Cancel','Close','Login','Logout')", name='CK_activity_logs_action'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_activity_logs_actor', 'activity_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('IDX_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index('IDX_activity_logs_module', 'activity_logs', ['module_name', 'created_at'], unique=False)
    op.create_table('asset_category_attributes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('attribute_key', sa.String(length=50), nullable=False),
    sa.Column('attribute_label', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('select_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("data_type IN ('TEXT','NUMBER','DATE','BOOLEAN','SELECT')", name='CK_asset_category_attributes_data_type'),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'attribute_key', name='UK_category_attribute')
    )
    op.create_index('IDX_category_attributes_category', 'asset_category_attributes', ['category_id'], unique=False)
    op.create_table('asset_status_transition_rules',
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('requires_permission', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['requires_permission'], ['permissions.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('from_status', 'to_status')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_tag', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('qr_code_value', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('condition', sa.String(length=20), server_default='Good', nullable=False),
    sa.Column('current_status', sa.String(length=20), server_default='Available', nullable=False),
    sa.Column('current_location_id', sa.UUID(), nullable=True),
    sa.Column('owning_department_id', sa.UUID(), nullable=True),
    sa.Column('current_holder_employee_id', sa.UUID(), nullable=True),
    sa.Column('is_bookable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('warranty_expiry_date', sa.Date(), nullable=True),
    sa.Column('expected_retirement_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("condition IN ('New','Good','Fair','Poor','Damaged')", name='CK_assets_condition'),
    sa.CheckConstraint("current_status IN ('Available','Allocated','Reserved','Under Maintenance','Lost','Retired','Disposed')", name='CK_assets_status'),
    sa.CheckConstraint('acquisition_cost >= 0', name='CK_assets_acquisition_cost_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_holder_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_location_id'], ['asset_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owning_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag')
    )
    op.create_index('IDX_assets_bookable', 'assets', ['is_bookable'], unique=False, postgresql_where=sa.text('is_bookable = TRUE'))
    op.create_index('IDX_assets_category_status', 'assets', ['category_id', 'current_status'], unique=False)
    op.create_index('IDX_assets_department_status', 'assets', ['owning_department_id', 'current_status'], unique=False)
    op.create_index('IDX_assets_directory_cover', 'assets', ['current_status', 'category_id'], unique=False, postgresql_include=['id', 'asset_tag', 'name', 'current_location_id'])
    op.create_index('IDX_assets_holder', 'assets', ['current_holder_employee_id'], unique=False, postgresql_where=sa.text('current_holder_employee_id IS NOT NULL'))
    op.create_index('IDX_assets_retirement', 'assets', ['expected_retirement_date'], unique=False, postgresql_where=sa.text("current_status NOT IN ('Retired','Disposed')"))
    op.create_index('IDX_assets_status', 'assets', ['current_status'], unique=False)
    op.create_index('UK_assets_qr', 'assets', ['qr_code_value'], unique=True, postgresql_where=sa.text('qr_code_value IS NOT NULL'))
    op.create_index('UK_assets_serial', 'assets', ['serial_number'], unique=True, postgresql_where=sa.text('serial_number IS NOT NULL'))
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=15), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('Asset','MaintenanceRequest','AuditCycleItem','TransferRequest')", name='CK_attachments_entity_type'),
    sa.CheckConstraint("file_type IN ('Photo','Document')", name='CK_attachments_file_type'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_attachments_entity', 'attachments', ['entity_type', 'entity_id'], unique=False)
    op.create_table('audit_cycles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cycle_name', sa.String(length=150), nullable=False),
    sa.Column('scope_department_id', sa.UUID(), nullable=True),
    sa.Column('scope_location_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Planned', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Planned','In Progress','Closed')", name='CK_audit_cycles_status'),
    sa.CheckConstraint('end_date >= start_date', name='CK_audit_cycles_dates'),
    sa.ForeignKeyConstraint(['closed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scope_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_location_id'], ['asset_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_audit_cycles_dates', 'audit_cycles', ['start_date', 'end_date'], unique=False)
    op.create_index('IDX_audit_cycles_department', 'audit_cycles', ['scope_department_id'], unique=False)
    op.create_index('IDX_audit_cycles_status', 'audit_cycles', ['status'], unique=False)
    op.create_table('department_closure',
    sa.Column('ancestor_id', sa.UUID(), nullable=False),
    sa.Column('descendant_id', sa.UUID(), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id')
    )
    op.create_index('IDX_dept_closure_descendant', 'department_closure', ['descendant_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='UK_devices_user_fingerprint')
    )
    op.create_index('IDX_devices_user', 'devices', ['user_id'], unique=False)
    op.create_table('fact_allocation',
    sa.Column('allocation_sk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('start_date_key', sa.Integer(), nullable=False),
    sa.Column('end_date_key', sa.Integer(), nullable=True),
    sa.Column('asset_sk', sa.BigInteger(), nullable=False),
    sa.Column('department_sk', sa.BigInteger(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_sk'], ['dim_asset.asset_sk'], ),
    sa.ForeignKeyConstraint(['department_sk'], ['dim_department.department_sk'], ),
    sa.ForeignKeyConstraint(['end_date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['start_date_key'], ['dim_date.date_key'], ),
    sa.PrimaryKeyConstraint('allocation_sk'),
    sa.UniqueConstraint('allocation_id')
    )
    op.create_index('IDX_fact_allocation_asset', 'fact_allocation', ['asset_sk'], unique=False)
    op.create_index('IDX_fact_allocation_dept', 'fact_allocation', ['department_sk'], unique=False)
    op.create_index('IDX_fact_allocation_start_date', 'fact_allocation', ['start_date_key'], unique=False)
    op.create_table('fact_asset_utilization',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('asset_sk', sa.BigInteger(), nullable=False),
    sa.Column('department_sk', sa.BigInteger(), nullable=True),
    sa.Column('is_allocated', sa.Boolean(), nullable=False),
    sa.Column('is_idle', sa.Boolean(), nullable=False),
    sa.Column('days_since_last_use', sa.Integer(), nullable=True),
    sa.Column('booking_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['asset_sk'], ['dim_asset.asset_sk'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['department_sk'], ['dim_department.department_sk'], ),
    sa.PrimaryKeyConstraint('date_key', 'asset_sk')
    )
    op.create_index('IDX_fact_utilization_asset', 'fact_asset_utilization', ['asset_sk'], unique=False)
    op.create_index('IDX_fact_utilization_date', 'fact_asset_utilization', ['date_key'], unique=False)
    op.create_index('IDX_fact_utilization_dept', 'fact_asset_utilization', ['department_sk'], unique=False)
    op.create_table('fact_maintenance',
    sa.Column('maintenance_sk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('maintenance_request_id', sa.UUID(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('asset_sk', sa.BigInteger(), nullable=False),
    sa.Column('category_sk', sa.BigInteger(), nullable=False),
    sa.Column('days_to_approve', sa.Integer(), nullable=True),
    sa.Column('days_to_resolve', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['asset_sk'], ['dim_asset.asset_sk'], ),
    sa.ForeignKeyConstraint(['category_sk'], ['dim_category.category_sk'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], ),
    sa.PrimaryKeyConstraint('maintenance_sk'),
    sa.UniqueConstraint('maintenance_request_id')
    )
    op.create_index('IDX_fact_maintenance_asset', 'fact_maintenance', ['asset_sk'], unique=False)
    op.create_index('IDX_fact_maintenance_category', 'fact_maintenance', ['category_sk'], unique=False)
    op.create_index('IDX_fact_maintenance_date', 'fact_maintenance', ['date_key'], unique=False)
    op.create_table('fact_resource_bookings',
    sa.Column('booking_sk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('start_time_key', sa.SmallInteger(), nullable=False),
    sa.Column('asset_sk', sa.BigInteger(), nullable=False),
    sa.Column('department_sk', sa.BigInteger(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['asset_sk'], ['dim_asset.asset_sk'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['department_sk'], ['dim_department.department_sk'], ),
    sa.ForeignKeyConstraint(['start_time_key'], ['dim_time_of_day.time_key'], ),
    sa.PrimaryKeyConstraint('booking_sk'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('IDX_fact_bookings_asset', 'fact_resource_bookings', ['asset_sk'], unique=False)
    op.create_index('IDX_fact_bookings_date', 'fact_resource_bookings', ['date_key'], unique=False)
    op.create_index('IDX_fact_bookings_heatmap', 'fact_resource_bookings', ['start_time_key', 'date_key'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('was_successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_login_attempts_email', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('IDX_login_attempts_ip', 'login_attempts', ['ip_address'], unique=False)
    op.create_index('IDX_login_attempts_user', 'login_attempts', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=15), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("channel IN ('InApp','Email')", name='CK_notification_preferences_channel'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'notification_type', 'channel')
    )
    op.create_index('IDX_notification_preferences_user', 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Alert','Approval','Booking')", name='CK_notifications_category'),
    sa.CheckConstraint("notification_type IN ('AssetAssigned','MaintenanceApproved','MaintenanceRejected','BookingConfirmed','BookingCancelled','BookingReminder','TransferApproved','OverdueReturn','AuditDiscrepancy')", name='CK_notifications_type'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_notifications_category', 'notifications', ['recipient_user_id', 'category', 'created_at'], unique=False)
    op.create_index('IDX_notifications_recipient_unread', 'notifications', ['recipient_user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('IDX_notifications_reference', 'notifications', ['reference_type', 'reference_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('IDX_password_reset_tokens_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('permission_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('IDX_role_permissions_permission', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('user_auth_providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.SmallInteger(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['authentication_providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='UK_user_auth_providers')
    )
    op.create_index('IDX_user_auth_providers_user', 'user_auth_providers', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('UK_user_profiles_phone', 'user_profiles', ['phone_number'], unique=True)
    op.create_index('UK_user_profiles_user', 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('department_scope_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_scope_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('IDX_user_roles_user', 'user_roles', ['user_id'], unique=False)
    op.create_index('UK_user_roles_active', 'user_roles', ['user_id', 'role_id', 'department_scope_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('user_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_user_status_history_user', 'user_status_history', ['user_id', 'changed_at'], unique=False)
    op.create_table('user_verifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verification_type', sa.String(length=20), nullable=False),
    sa.Column('verification_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_type IN ('Email')", name='CK_user_verifications_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index('IDX_user_verifications_user', 'user_verifications', ['user_id'], unique=False)
    op.create_index('UK_user_verifications_token', 'user_verifications', ['verification_token'], unique=True)
    op.create_table('asset_allocations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('allocated_to_employee_id', sa.UUID(), nullable=True),
    sa.Column('allocated_to_department_id', sa.UUID(), nullable=True),
    sa.Column('allocated_by', sa.UUID(), nullable=False),
    sa.Column('allocation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_condition', sa.String(length=20), nullable=True),
    sa.Column('return_notes', sa.Text(), nullable=True),
    sa.Column('returned_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("return_condition IN ('New','Good','Fair','Poor','Damaged')", name='CK_asset_allocations_return_condition'),
    sa.CheckConstraint("status IN ('Active','Returned','Overdue','Lost')", name='CK_asset_allocations_status'),
    sa.CheckConstraint('(allocated_to_employee_id IS NOT NULL) <> (allocated_to_department_id IS NOT NULL)', name='CK_asset_allocations_one_target'),
    sa.ForeignKeyConstraint(['allocated_by'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['allocated_to_department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['allocated_to_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['returned_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_asset_allocations_asset_history', 'asset_allocations', ['asset_id', 'allocation_date'], unique=False)
    op.create_index('IDX_asset_allocations_department', 'asset_allocations', ['allocated_to_department_id', 'status'], unique=False)
    op.create_index('IDX_asset_allocations_employee', 'asset_allocations', ['allocated_to_employee_id', 'status'], unique=False)
    op.create_index('IDX_asset_allocations_overdue', 'asset_allocations', ['expected_return_date'], unique=False, postgresql_where=sa.text("status = 'Active'"))
    op.create_index('UK_asset_allocations_one_active', 'asset_allocations', ['asset_id'], unique=True, postgresql_where=sa.text("status = 'Active'"))
    op.create_table('asset_custom_attribute_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_id'], ['asset_category_attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'attribute_id', name='UK_asset_attribute')
    )
    op.create_index('IDX_attribute_values_attribute', 'asset_custom_attribute_values', ['attribute_id'], unique=False)
    op.create_table('asset_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reference_type IN ('Allocation','Booking','Maintenance','Audit','Manual')", name='CK_asset_status_history_reference_type'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_asset_status_history_asset', 'asset_status_history', ['asset_id', 'changed_at'], unique=False)
    op.create_index('IDX_asset_status_history_changed_at', 'asset_status_history', ['changed_at'], unique=False)
    op.create_index('IDX_asset_status_history_reference', 'asset_status_history', ['reference_type', 'reference_id'], unique=False)
    op.create_table('audit_cycle_auditors',
    sa.Column('audit_cycle_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_cycle_id'], ['audit_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_cycle_id', 'employee_id')
    )
    op.create_index('IDX_audit_auditors_employee', 'audit_cycle_auditors', ['employee_id'], unique=False)
    op.create_table('audit_cycle_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('audit_cycle_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('expected_location_id', sa.UUID(), nullable=True),
    sa.Column('verification_status', sa.String(length=15), server_default='Pending', nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.CheckConstraint("verification_status IN ('Pending','Verified','Missing','Damaged')", name='CK_audit_cycle_items_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['audit_cycle_id'], ['audit_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expected_location_id'], ['asset_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_cycle_id', 'asset_id', name='UK_audit_cycle_items')
    )
    op.create_index('IDX_audit_items_asset', 'audit_cycle_items', ['asset_id'], unique=False)
    op.create_index('IDX_audit_items_cycle_status', 'audit_cycle_items', ['audit_cycle_id', 'verification_status'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_code', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_employee_id', sa.UUID(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='Medium', nullable=False),
    sa.Column('status', sa.String(length=25), server_default='Pending', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('Low','Medium','High','Critical')", name='CK_maintenance_requests_priority'),
    sa.CheckConstraint("status IN ('Pending','Approved','Rejected','Technician Assigned','In Progress','Resolved')", name='CK_maintenance_requests_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raised_by_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['maintenance_technicians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code')
    )
    op.create_index('IDX_maintenance_asset', 'maintenance_requests', ['asset_id', 'created_at'], unique=False)
    op.create_index('IDX_maintenance_kanban', 'maintenance_requests', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('IDX_maintenance_pending', 'maintenance_requests', ['status'], unique=False, postgresql_where=sa.text("status = 'Pending'"))
    op.create_index('IDX_maintenance_technician', 'maintenance_requests', ['technician_id', 'status'], unique=False)
    op.create_table('resource_bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('booked_by_employee_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Upcoming', nullable=False),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Upcoming','Ongoing','Completed','Cancelled')", name='CK_resource_bookings_status'),
    sa.CheckConstraint('end_datetime > start_datetime', name='CK_resource_bookings_end_after_start'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booked_by_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_resource_bookings_asset_time', 'resource_bookings', ['asset_id', 'start_datetime'], unique=False)
    op.create_index('IDX_resource_bookings_employee', 'resource_bookings', ['booked_by_employee_id', 'status'], unique=False)
    op.create_index('IDX_resource_bookings_reminder_pending', 'resource_bookings', ['start_datetime'], unique=False, postgresql_where=sa.text("status = 'Upcoming' AND reminder_sent_at IS NULL"))
    op.create_index('IDX_resource_bookings_status_upcoming', 'resource_bookings', ['status', 'start_datetime'], unique=False, postgresql_where=sa.text("status IN ('Upcoming','Ongoing')"))
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token_hash', sa.Text(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_hash'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('IDX_user_sessions_active', 'user_sessions', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('IDX_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('asset_transfer_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('current_allocation_id', sa.UUID(), nullable=False),
    sa.Column('from_employee_id', sa.UUID(), nullable=True),
    sa.Column('to_employee_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Requested', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Requested','Approved','Rejected','Completed','Cancelled')", name='CK_asset_transfer_requests_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_allocation_id'], ['asset_allocations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_transfer_requests_asset', 'asset_transfer_requests', ['asset_id', 'status'], unique=False)
    op.create_index('IDX_transfer_requests_pending', 'asset_transfer_requests', ['status'], unique=False, postgresql_where=sa.text("status = 'Requested'"))
    op.create_index('IDX_transfer_requests_to_employee', 'asset_transfer_requests', ['to_employee_id'], unique=False)
    op.create_table('audit_discrepancy_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audit_cycle_id', sa.UUID(), nullable=False),
    sa.Column('audit_cycle_item_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('discrepancy_type', sa.String(length=15), nullable=False),
    sa.Column('auto_generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolution_status', sa.String(length=15), server_default='Open', nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("discrepancy_type IN ('Missing','Damaged')", name='CK_audit_discrepancy_reports_type'),
    sa.CheckConstraint("resolution_status IN ('Open','Resolved')", name='CK_audit_discrepancy_reports_resolution'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['audit_cycle_id'], ['audit_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audit_cycle_item_id'], ['audit_cycle_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_cycle_item_id')
    )
    op.create_index('IDX_discrepancy_cycle', 'audit_discrepancy_reports', ['audit_cycle_id'], unique=False)
    op.create_index('IDX_discrepancy_open', 'audit_discrepancy_reports', ['resolution_status'], unique=False, postgresql_where=sa.text("resolution_status = 'Open'"))
    op.create_table('maintenance_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('maintenance_request_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=25), nullable=True),
    sa.Column('new_status', sa.String(length=25), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IDX_maintenance_status_history_request', 'maintenance_status_history', ['maintenance_request_id', 'changed_at'], unique=False)

    # ── Deferred/circular FKs (added after all tables exist) ─────────────────
    # employees.user_id → users.id
    op.create_foreign_key(
        'FK_employees_user', 'employees', 'users',
        ['user_id'], ['id'], ondelete='RESTRICT'
    )
    # employees.department_id → departments.id  (DEFERRABLE INITIALLY DEFERRED)
    op.execute(
        "ALTER TABLE employees ADD CONSTRAINT FK_employees_department "
        "FOREIGN KEY (department_id) REFERENCES departments(id) "
        "ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;"
    )
    # departments.created_by → users.id
    op.create_foreign_key(
        'FK_departments_created_by', 'departments', 'users',
        ['created_by'], ['id'], ondelete='RESTRICT'
    )
    # departments.head_employee_id → employees.id  (DEFERRABLE INITIALLY DEFERRED)
    op.execute(
        "ALTER TABLE departments ADD CONSTRAINT FK_departments_head_employee "
        "FOREIGN KEY (head_employee_id) REFERENCES employees(id) "
        "ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;"
    )

    # ── Post-table extras ─────────────────────────────────────────────────────
    # GIN full-text index on assets (name, serial, tag)

    op.execute("""
        CREATE INDEX IF NOT EXISTS FTX_assets_search
        ON assets
        USING GIN (
            to_tsvector('simple',
                name || ' ' ||
                coalesce(serial_number, '') || ' ' ||
                asset_tag
            )
        );
    """)
    # Trigram index for partial/fuzzy asset name search
    op.execute("""
        CREATE INDEX IF NOT EXISTS IDX_assets_name_trgm
        ON assets USING GIN (name gin_trgm_ops);
    """)
    # Booking overlap exclusion (requires btree_gist)
    op.execute("""
        ALTER TABLE resource_bookings
        ADD CONSTRAINT EXCL_resource_bookings_no_overlap
        EXCLUDE USING gist (
            asset_id WITH =,
            tstzrange(start_datetime, end_datetime, '[)') WITH &&
        )
        WHERE (status <> 'Cancelled');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE resource_bookings DROP CONSTRAINT IF EXISTS EXCL_resource_bookings_no_overlap;")
    op.execute("DROP INDEX IF EXISTS FTX_assets_search;")
    op.execute("DROP INDEX IF EXISTS IDX_assets_name_trgm;")
    op.drop_index('IDX_maintenance_status_history_request', table_name='maintenance_status_history')
    op.drop_table('maintenance_status_history')
    op.drop_index('IDX_discrepancy_open', table_name='audit_discrepancy_reports', postgresql_where=sa.text("resolution_status = 'Open'"))
    op.drop_index('IDX_discrepancy_cycle', table_name='audit_discrepancy_reports')
    op.drop_table('audit_discrepancy_reports')
    op.drop_index('IDX_transfer_requests_to_employee', table_name='asset_transfer_requests')
    op.drop_index('IDX_transfer_requests_pending', table_name='asset_transfer_requests', postgresql_where=sa.text("status = 'Requested'"))
    op.drop_index('IDX_transfer_requests_asset', table_name='asset_transfer_requests')
    op.drop_table('asset_transfer_requests')
    op.drop_index('IDX_user_sessions_user', table_name='user_sessions')
    op.drop_index('IDX_user_sessions_active', table_name='user_sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('user_sessions')
    op.drop_index('IDX_resource_bookings_status_upcoming', table_name='resource_bookings', postgresql_where=sa.text("status IN ('Upcoming','Ongoing')"))
    op.drop_index('IDX_resource_bookings_reminder_pending', table_name='resource_bookings', postgresql_where=sa.text("status = 'Upcoming' AND reminder_sent_at IS NULL"))
    op.drop_index('IDX_resource_bookings_employee', table_name='resource_bookings')
    op.drop_index('IDX_resource_bookings_asset_time', table_name='resource_bookings')
    op.drop_table('resource_bookings')
    op.drop_index('IDX_maintenance_technician', table_name='maintenance_requests')
    op.drop_index('IDX_maintenance_pending', table_name='maintenance_requests', postgresql_where=sa.text("status = 'Pending'"))
    op.drop_index('IDX_maintenance_kanban', table_name='maintenance_requests')
    op.drop_index('IDX_maintenance_asset', table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index('IDX_audit_items_cycle_status', table_name='audit_cycle_items')
    op.drop_index('IDX_audit_items_asset', table_name='audit_cycle_items')
    op.drop_table('audit_cycle_items')
    op.drop_index('IDX_audit_auditors_employee', table_name='audit_cycle_auditors')
    op.drop_table('audit_cycle_auditors')
    op.drop_index('IDX_asset_status_history_reference', table_name='asset_status_history')
    op.drop_index('IDX_asset_status_history_changed_at', table_name='asset_status_history')
    op.drop_index('IDX_asset_status_history_asset', table_name='asset_status_history')
    op.drop_table('asset_status_history')
    op.drop_index('IDX_attribute_values_attribute', table_name='asset_custom_attribute_values')
    op.drop_table('asset_custom_attribute_values')
    op.drop_index('UK_asset_allocations_one_active', table_name='asset_allocations', postgresql_where=sa.text("status = 'Active'"))
    op.drop_index('IDX_asset_allocations_overdue', table_name='asset_allocations', postgresql_where=sa.text("status = 'Active'"))
    op.drop_index('IDX_asset_allocations_employee', table_name='asset_allocations')
    op.drop_index('IDX_asset_allocations_department', table_name='asset_allocations')
    op.drop_index('IDX_asset_allocations_asset_history', table_name='asset_allocations')
    op.drop_table('asset_allocations')
    op.drop_index('UK_user_verifications_token', table_name='user_verifications')
    op.drop_index('IDX_user_verifications_user', table_name='user_verifications')
    op.drop_table('user_verifications')
    op.drop_index('IDX_user_status_history_user', table_name='user_status_history')
    op.drop_table('user_status_history')
    op.drop_index('UK_user_roles_active', table_name='user_roles', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('IDX_user_roles_user', table_name='user_roles')
    op.drop_index('IDX_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('UK_user_profiles_user', table_name='user_profiles')
    op.drop_index('UK_user_profiles_phone', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('IDX_user_auth_providers_user', table_name='user_auth_providers')
    op.drop_table('user_auth_providers')
    op.drop_index('IDX_role_permissions_permission', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('IDX_password_reset_tokens_user', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('IDX_notifications_reference', table_name='notifications')
    op.drop_index('IDX_notifications_recipient_unread', table_name='notifications')
    op.drop_index('IDX_notifications_category', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('IDX_notification_preferences_user', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('IDX_login_attempts_user', table_name='login_attempts')
    op.drop_index('IDX_login_attempts_ip', table_name='login_attempts')
    op.drop_index('IDX_login_attempts_email', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index('IDX_fact_bookings_heatmap', table_name='fact_resource_bookings')
    op.drop_index('IDX_fact_bookings_date', table_name='fact_resource_bookings')
    op.drop_index('IDX_fact_bookings_asset', table_name='fact_resource_bookings')
    op.drop_table('fact_resource_bookings')
    op.drop_index('IDX_fact_maintenance_date', table_name='fact_maintenance')
    op.drop_index('IDX_fact_maintenance_category', table_name='fact_maintenance')
    op.drop_index('IDX_fact_maintenance_asset', table_name='fact_maintenance')
    op.drop_table('fact_maintenance')
    op.drop_index('IDX_fact_utilization_dept', table_name='fact_asset_utilization')
    op.drop_index('IDX_fact_utilization_date', table_name='fact_asset_utilization')
    op.drop_index('IDX_fact_utilization_asset', table_name='fact_asset_utilization')
    op.drop_table('fact_asset_utilization')
    op.drop_index('IDX_fact_allocation_start_date', table_name='fact_allocation')
    op.drop_index('IDX_fact_allocation_dept', table_name='fact_allocation')
    op.drop_index('IDX_fact_allocation_asset', table_name='fact_allocation')
    op.drop_table('fact_allocation')
    op.drop_index('IDX_devices_user', table_name='devices')
    op.drop_table('devices')
    op.drop_index('IDX_dept_closure_descendant', table_name='department_closure')
    op.drop_table('department_closure')
    op.drop_index('IDX_audit_cycles_status', table_name='audit_cycles')
    op.drop_index('IDX_audit_cycles_department', table_name='audit_cycles')
    op.drop_index('IDX_audit_cycles_dates', table_name='audit_cycles')
    op.drop_table('audit_cycles')
    op.drop_index('IDX_attachments_entity', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('UK_assets_serial', table_name='assets', postgresql_where=sa.text('serial_number IS NOT NULL'))
    op.drop_index('UK_assets_qr', table_name='assets', postgresql_where=sa.text('qr_code_value IS NOT NULL'))
    op.drop_index('IDX_assets_status', table_name='assets')
    op.drop_index('IDX_assets_retirement', table_name='assets', postgresql_where=sa.text("current_status NOT IN ('Retired','Disposed')"))
    op.drop_index('IDX_assets_holder', table_name='assets', postgresql_where=sa.text('current_holder_employee_id IS NOT NULL'))
    op.drop_index('IDX_assets_directory_cover', table_name='assets', postgresql_include=['id', 'asset_tag', 'name', 'current_location_id'])
    op.drop_index('IDX_assets_department_status', table_name='assets')
    op.drop_index('IDX_assets_category_status', table_name='assets')
    op.drop_index('IDX_assets_bookable', table_name='assets', postgresql_where=sa.text('is_bookable = TRUE'))
    op.drop_table('assets')
    op.drop_table('asset_status_transition_rules')
    op.drop_index('IDX_category_attributes_category', table_name='asset_category_attributes')
    op.drop_table('asset_category_attributes')
    op.drop_index('IDX_activity_logs_module', table_name='activity_logs')
    op.drop_index('IDX_activity_logs_entity', table_name='activity_logs')
    op.drop_index('IDX_activity_logs_actor', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('IDX_users_status', table_name='users')
    op.drop_index('IDX_users_locked', table_name='users', postgresql_where=sa.text('locked_until IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('UK_roles_name', table_name='roles')
    op.drop_index('PK_roles', table_name='roles')
    op.drop_table('roles')
    op.drop_index('UK_permissions_name', table_name='permissions')
    op.drop_index('PK_permissions', table_name='permissions')
    op.drop_index('IDX_permissions_module', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('IDX_maintenance_technicians_specialization', table_name='maintenance_technicians')
    op.drop_index('IDX_maintenance_technicians_active', table_name='maintenance_technicians')
    op.drop_table('maintenance_technicians')
    op.drop_table('entity_code_sequences')
    op.drop_index('UK_employees_user', table_name='employees')
    op.drop_index('UK_employees_code', table_name='employees')
    op.drop_index('IDX_employees_status', table_name='employees')
    op.drop_index('IDX_employees_search', table_name='employees', postgresql_include=['id', 'employee_code'])
    op.drop_index('IDX_employees_manager', table_name='employees')
    op.drop_index('IDX_employees_department', table_name='employees')
    op.drop_table('employees')
    op.drop_table('dim_time_of_day')
    op.drop_index('IDX_dim_employee_natural', table_name='dim_employee')
    op.drop_table('dim_employee')
    op.drop_index('IDX_dim_department_natural', table_name='dim_department')
    op.drop_table('dim_department')
    op.drop_index('IDX_dim_date_full_date', table_name='dim_date')
    op.drop_table('dim_date')
    op.drop_index('IDX_dim_category_natural', table_name='dim_category')
    op.drop_table('dim_category')
    op.drop_index('IDX_dim_asset_natural', table_name='dim_asset')
    op.drop_index('IDX_dim_asset_current', table_name='dim_asset', postgresql_where=sa.text('is_current = TRUE'))
    op.drop_table('dim_asset')
    op.drop_index('UK_departments_code', table_name='departments', postgresql_where=sa.text('code IS NOT NULL'))
    op.drop_index('IDX_departments_status', table_name='departments')
    op.drop_index('IDX_departments_parent', table_name='departments')
    op.drop_index('IDX_departments_head', table_name='departments')
    op.drop_table('departments')
    op.drop_index('UK_auth_providers_name', table_name='authentication_providers')
    op.drop_table('authentication_providers')
    op.drop_index('IDX_asset_locations_type', table_name='asset_locations')
    op.drop_index('IDX_asset_locations_parent', table_name='asset_locations')
    op.drop_table('asset_locations')
    op.drop_index('UK_asset_categories_name_lower', table_name='asset_categories')
    op.drop_index('IDX_asset_categories_parent', table_name='asset_categories')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
